name: service1-test-run-template
on:
  # push:
  # branches: [ "main" ]
  # Runs this workflow every day at 8 am
  # schedule:
  #  - cron: '0 8 * * *'

jobs:
  test-Safe-APIs:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v2
        with: 
          node-version: '22.x'

      # Installs newman and reporter dependencies
      - name: Install newman and reporter dependencies
        run: |
          npm install -g newman
          npm install -g newman-reporter-ctrf-json
      
      # Creates directory for run results
      - name: Create directory for run results
        run: mkdir -p ./reports
   
      # Runs Rick and Morty Postman collection
      - name: Run Rick and Morty Postman collection
        run: |
          newman run ./collections/rick_and_morty_collection.json -e ./collections/rick_and_morty_environment.json --delay-request 40 -r cli,ctrf-json --reporter-ctrf-json-output-file api-test_run-report.json --reporter-ctrf-json-output-dir ./reports

     # Generates test report
      - name: Generate test report
        run: npx github-actions-ctrf community ./reports/api-test_run-report.json summary-short
        if: always()
